//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlUnit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class guyunhaoEntities : DbContext
    {
        public guyunhaoEntities()
            : base("name=guyunhaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<farm> farm { get; set; }
        public virtual DbSet<machine> machine { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<uploadfiles> uploadfiles { get; set; }
    }
}
