//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine
    {
        public Nullable<int> farmid { get; set; }
        public string signal { get; set; }
        public Nullable<int> type { get; set; }
        public string name { get; set; }
        public int id { get; set; }
    }
}
