//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public Nullable<int> MachineType { get; set; }
        public Nullable<decimal> min_attr_value { get; set; }
        public Nullable<decimal> max_attr_value { get; set; }
        public Nullable<decimal> attr_value { get; set; }
        public string attr_name { get; set; }
        public Nullable<sbyte> isRuning { get; set; }
        public int MachineId { get; set; }
        public int id { get; set; }
    }
}
