//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu
    {
        public int id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public string psw { get; set; }
        public string headUrl { get; set; }
        public string pcode { get; set; }
    }
}
